### ISSUE TITLE
My config literally stop working out of nowhere and it gives me this error

### ISSUE THREAD

**Issue by hrqmonteiro** [udayvir-singh/hibiscus.nvim#10]
![Screenshot from 2023-01-18 11-33-33](https://user-images.githubusercontent.com/17055027/213198745-e7d0e036-9845-4f9f-b1d3-37c7b4f853da.png)

What is happening??

I haven't changed anything in my config, i just ran `PackerUpdate` and now everything is broken and apparently is because of this 'exec' function?

**Comment by hrqmonteiro** [comment]
Also this one?

![Screenshot from 2023-01-18 11-35-19](https://user-images.githubusercontent.com/17055027/213199091-6fe22423-d510-4c29-839e-acc097b56470.png)

**Comment by udayvir-singh** [comment]
@hrqmonteiro refer to commit [f73a34](https://github.com/udayvir-singh/hibiscus.nvim/commit/f73a34d3305bf4f02f3b63e5a174b767f230241a).

Also remember to lock hibiscus version like this:
```lua
-- ~/.config/nvim/plugin/0-tangerine.lua

-- pick your plugin manager, default [standalone]
local pack = "tangerine" or "packer" or "paq"

local function bootstrap(url, ref)
	local name = url:gsub(".*/", "")
	local path = vim.fn.stdpath [[data]] .. "/site/pack/".. pack .. "/start/" .. name

	if vim.fn.isdirectory(path) == 0 then
		print(name .. ": installing in data dir...")

		vim.fn.system {"git", "clone", url, path}
		if ref then
			vim.fn.system {"git", "-C", path, "checkout", ref}
		end

		vim.cmd [[redraw]]
		print(name .. ": finished installing")
	end
end

bootstrap("https://github.com/udayvir-singh/hibiscus.nvim", "v1.4")
```

and add these lines to packer:
```fennel
(packer!
  (use! :udayvir-singh/hibiscus.nvim
        :tag "v1.4"))
```
