### ISSUE TITLE
how to set listchars

### ISSUE THREAD

**Issue by kalxd** [udayvir-singh/hibiscus.nvim#11]
hi all.
I have installed this plugin of  latest version, and try to `set!`  `lcs`, but I do not know how to use it correctly.

here is my code:

```fennel
(import-macros {: set!} :hibiscus.vim)

(set! list true)
;; (set! listchars :eol "↵")  ;; yes, it works
(set! listchars "tab:→") ;; but this line failed
```
`(set! listchars "tab:→")` always failed, I also tried `(tset vim.opt "listchars" {:eol "↵" :tab "→"})`, and didn't work either.

So how do I set `listchars` correctly?
thanks.

**Comment by udayvir-singh** [comment]
You need to put at least two characters in `tab` option of `listchars`, see `:h listchars`.

So try this instead:
```fennel
(set! list)
(set! listchars "tab:-->")
```
