### ISSUE TITLE
[Feature Request] inversion support for `set!`

### ISSUE THREAD

**Issue by alexmozaidze** [udayvir-singh/hibiscus.nvim#12]
Make the following possible
```fnl
(set! wrap!)
(set! invwrap)
```

**Comment by udayvir-singh** [comment]
@alexmozaidze Inversion support is already builtin. add the `no` prefix in front of a option.

```fennel
(set! nowrap)
```

**Comment by alexmozaidze** [comment]
Huh, I thought that just disables the option.

**Comment by alexmozaidze** [comment]
I don't think it works. The following keybinds do not inverse the options, they just disable them
```fennel
(map! [n] "<leader>tr" #(set! nocursorline))
(map! [n] "<leader>tc" #(set! nocursorcolumn))
```

**Comment by udayvir-singh** [comment]
@alexmozaidze If you want to toggle and option on/off just use the `not` operator, here is an example from my dotfiles:

```fennel
(map! [n] :<leader>aw '(setlocal! wrap (not vim.o.wrap)))
(map! [n] :<leader>as '(setlocal! spell (not vim.o.spell)))
```

**Comment by alexmozaidze** [comment]
It would've been nice to have a toggle via `!` like in vimscript. I presume that something like `wrap!` is interpreted as a single identifier, but since no options use `!` in their name, it would be safe to assume that if the last character is `!`, then toggle the option and error if there is a third argument. If you don't mind, can you tell me where I should look into to implement this logic?

**Comment by udayvir-singh** [comment]
@alexmozaidze Ok, I will implement it myself, shouldn't be much of a hassle anyways.
