### ISSUE TITLE
[Feature Request] add macros for Lazy plugin manager 

### ISSUE THREAD

**Issue by alexmozaidze** [udayvir-singh/hibiscus.nvim#13]

**Comment by udayvir-singh** [comment]
@alexmozaidze I did try to get lazy working with tangerine but I couldn't find out a way to do so, I personally just use packer with impatient and that gives me the same functionality as lazy without any conflicts with tangerine.

**Comment by udayvir-singh** [comment]
@alexmozaidze If you can find a way to get lazy working with tangerine in fennel, be sure to tell me how you did it.

**Comment by udayvir-singh** [comment]
@alexmozaidze Just checked the lazy plugin manager's schema and it doesn't seem to need any help of macros, The reason why macros were added for packer were because packer used a mix of a array and hashtable in it's schema which made the fennel code look awkward, like this:

```fennel
(packer.startup
  (lambda [use]
    (use {1 :plugin-name
            :tag "1.x" 
            :depends {
              1 :another-plugin
              :tag "1.x"}})))
```

**Comment by udayvir-singh** [comment]
@alexmozaidze I am assigning wontfix label to it as I don't personnaly use lazy, however you can submit a pr add support for lazy, just recycle the code from packer macro.

**Comment by alexmozaidze** [comment]
Lazy suffers from the exact same problem. Index `1` is for shorthand GitHub URL, and `url` is only for full git address.
