### ISSUE TITLE
'require config' on the packer macros are not working

### ISSUE THREAD

**Issue by hrqmonteiro** [udayvir-singh/hibiscus.nvim#2]
![image](https://user-images.githubusercontent.com/17055027/184367649-ed4fb25d-24b5-43b1-bef7-9f4f96992e9b.png)

I am trying to set the config files for the plugins by calling it inline when i set the plugins with `use!`, but it doesn't work.

The config file only works if i do the `require` separately (as you can see on the top of my file in the screenshot)

**Comment by udayvir-singh** [comment]
That happens because your config files are loaded before packer. That's why when you try to require plugin config files, they show errors because the plugins aren't loaded yet.

Hibiscus provides an addition option `module` on `use!` macro which requires that module for you, use it instead:
```fennel
(packer
  (use! :nvim-treesitter/nvim-treesitter
        :run    ":TSUpdate"
        :module "plugins.treesitter"))
```

**Comment by hrqmonteiro** [comment]
> That happens because your config files are loaded before packer. That's why when you try to require plugin config files, they show errors because the plugins aren't loaded yet.
> 
> Hibiscus provides an addition option `module` on `use!` macro which requires that module for you, use it instead:
> 
> ```fnl
> (packer
>   (use! :nvim-treesitter/nvim-treesitter
>         :run    ":TSUpdate"
>         :module "plugins.treesitter"))
> ```

That still doesn't work.

I did that with `lualine` and, as you can see in the screenshot, the config is not loading, so lualine is not appearing:

![Screenshot from 2022-08-12 14-30-54](https://user-images.githubusercontent.com/17055027/184412410-30982b8b-f8f5-4c88-9c3c-09419326f1f1.png)

**Comment by hrqmonteiro** [comment]
Hello?

**Comment by udayvir-singh** [comment]
@hrqmonteiro did you run `:PackerCompile`?
