### ISSUE TITLE
packer already has a "module" parameter

### ISSUE THREAD

**Issue by yshui** [udayvir-singh/hibiscus.nvim#9]
```
  module = string or list      -- Specifies Lua module names for require. When requiring a string which starts
                               -- with one of these module names, the plugin will be loaded.
```

**Comment by yshui** [comment]
I think instead of `:module "module.path"`, we could use `:config 'module.path` for loading module as config.

**Comment by udayvir-singh** [comment]
@yshui Thanks for pointing this out. `module` option has now been replaced with `require` option with commit [1ec614a](https://github.com/udayvir-singh/hibiscus.nvim/commit/1ec614a7969e6a474a72c775db6b7cc61dce54a8).

`require` option also accepts list of multiple modules:

```clojure
(use! :lspconfig
      :require ["lsp.diagnostic" "lsp.options" ...])
```

**Comment by yshui** [comment]
@udayvir-singh i think `:require` is not a very good choice as it can be confused with `:requires`.

**Comment by udayvir-singh** [comment]
@yshui I also thought about that at first, that's why I added `module` opt at first for a lack of better name. I am open any newer suggestions.

**Comment by yshui** [comment]
what about my suggestion above?

use `:config 'module`.

**Comment by udayvir-singh** [comment]
@yshui packing config handler and module loader into a single option will just create more confusion.

**Comment by yshui** [comment]
I have to disagree. It's appropriate to put it in `:config`, because that is what it is: a module used for config.

It is confusing when similar names mean _different_ things: `:require` and `:requires` are similar, but their meaning is completely different.

**Comment by udayvir-singh** [comment]
@yshui What if we add another option `:depends` which wraps `:requires`. It solve two problems:
- first it resolves the confusion with `:require`
- second it allows to configure dependencies without the current wacky syntax. Example:
```clojure
; BEFORE
(use! :some-plugin
      :requires [
        {1 :plugin-foo :run "xyz"}
        {1 :plugin-baz :config #(require :mod)}])

; AFTER
(use! :some-plugin
      :depends [
        [:plugin-foo :run "xyz"]
        [:plugin-baz :require "mod"]])
```

**Comment by yshui** [comment]
that looks good to me :+1:
